In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Goba,ET,2020-04-18 21:55:02,7.02,39.98,52.77,40,100,3.33
1,1,Tasiilaq,GL,2020-04-18 21:55:03,65.61,-37.64,33.80,80,100,14.99
2,2,Hilo,US,2020-04-18 21:55:03,19.73,-155.09,82.40,51,40,11.41
3,3,Verkh-Usugli,RU,2020-04-18 21:55:03,52.70,115.17,15.98,86,73,7.27
4,4,Hobart,AU,2020-04-18 21:54:59,-42.88,147.33,46.99,93,75,6.93

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [4]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)


# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

# Assign the figure variable.
fig =gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])

# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:

locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]


fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [9]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Hilo,US,2020-04-18 21:55:03,19.73,-155.09,82.40,51,40,11.41
6,6,Roebourne,AU,2020-04-18 21:55:04,-20.78,117.13,82.44,57,100,7.85
7,7,Rikitea,PF,2020-04-18 21:55:04,-23.12,-134.97,77.09,73,18,7.54
10,10,Avarua,CK,2020-04-18 21:55:05,-21.21,-159.78,80.60,74,54,6.93
11,11,Lorengau,PG,2020-04-18 21:55:06,-2.02,147.27,82.47,74,3,3.04
12,12,Parrita,CR,2020-04-18 21:55:06,9.52,-84.32,84.20,45,40,14.99
31,31,Abapo,BO,2020-04-18 21:55:12,-18.83,-63.47,82.06,20,12,5.46
35,35,Bengkulu,ID,2020-04-18 21:55:13,-3.80,102.27,76.73,85,100,4.03
38,38,Kavaratti,IN,2020-04-18 21:55:13,10.57,72.64,84.13,71,1,4.56
39,39,Butaritari,KI,2020-04-18 21:55:14,3.07,172.79,83.21,77,76,15.82

In [10]:
preferred_cities_df.count()

City_ID       170
City          170
Country       169
Date          170
Lat           170
Lng           170
Max Temp      170
Humidity      170
Cloudiness    170
Wind Speed    170
dtype: int64

In [11]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp    Lat     Lng Hotel Name
2         Hilo      US     82.40  19.73 -155.09
6    Roebourne      AU     82.44 -20.78  117.13
7      Rikitea      PF     77.09 -23.12 -134.97
10      Avarua      CK     80.60 -21.21 -159.78
11    Lorengau      PG     82.47  -2.02  147.27
12     Parrita      CR     84.20   9.52  -84.32
31       Abapo      BO     82.06 -18.83  -63.47
35    Bengkulu      ID     76.73  -3.80  102.27
38   Kavaratti      IN     84.13  10.57   72.64
39  Butaritari      KI     83.21   3.07  172.79

In [12]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [13]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [15]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except IndexError:
        print("Hotel not found... skipping.")



    # Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

          City Country  Max Temp    Lat     Lng                   Hotel Name
2         Hilo      US     82.40  19.73 -155.09          Hilo Hawaiian Hotel
6    Roebourne      AU     82.44 -20.78  117.13   Harding River Caravan Park
7      Rikitea      PF     77.09 -23.12 -134.97               Pension Maro'i
10      Avarua      CK     80.60 -21.21 -159.78                 Paradise Inn
11    Lorengau      PG     82.47  -2.02  147.27   Lorengau Harbourside Hotel
12     Parrita      CR     84.20   9.52  -84.32              Beso del Viento
31       Abapo      BO     82.06 -18.83  -63.47
35    Bengkulu      ID     76.73  -3.80  102.27         Grage Hotel Bengkulu
38   Kavaratti      IN     84.13  10.57   72.64  Bismillah Hotel And Lodging
39  Butaritari      KI     83.21   3.07  172.79           Isles Sunset Lodge

In [18]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]

max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

In [25]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [32]:
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [33]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))